server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musicdb
    username: music
    password: music123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123
  bucket: album-covers